version: "3"

services:
    api:
        build: .
        volumes:
            - ./app:/app
        ports:
            - "8000:8000"
        environment:
            DATABASE_URL: "postgresql://database:5432"
            PGDATABASE: "main"
            PGUSER: "root"
            PGPASSWORD: "toor"
        working_dir: /app
        depends_on:
            - "database"
    database:
        image: "postgres:12"
        volumes:
            - "database-data:/var/lib/postgresql/data/"
        env_file:
            - "app/data/db_init.env"
        ports:
            - "5432:5432"
volumes:
    database-data:
